Android.mk, droidmediacamera.cpp, droidmediacodec.cpp, droidmediarecorder.cpp, droidmediarecorder.h, hybris.c, private.h
droidmediarecorder is a set of API to enable the usage of android stagefright encoders directly by camera. This gives us the ability to push encoded video from camera.
=> add droidmediarecorder

minisf.cpp
Batterystats is a new service for tracking multimedia usage in Android 6+. Qualcomm blobs call it when the camera starts and stops. The calls don't seem to block UI, but some background threads do as they wait for the service manager to timeout.
In the longer term it may be useful to record this data in Sailfish.
=> [minisf] Add fake batterystats service. Contributes JB#37491

allocator.cpp, droidmedia.h, droidmediabuffer.cpp, droidmediacamera.cpp, droidmediacodec.cpp, droidmediaconvert.cpp, droidmediarecorder.cpp, hybris.c, minimedia.cpp, private.cpp
Added a getHandle method to export buffers to gstreamer-omx.
Added support for Android 7's VIDEO_BUFFER_MODE_BUFFER_QUEUE, passing video buffers from the camera to the codec. The output buffers of the codec are not permitted to use buffers, but by that point the video as been encoded to the cost isn't too bad.
=> Android 7 support

Android.mk, droidmediacamera.cpp, droidmediacodec.cpp, droidmediacodec.h, rpm/droidmedia.spec
Some cameras default to HAL3+, but have only partially implemented it. This adds an OBS prjconf/environment parameter to switch to use connectLegacy instead. Support for alternative video buffer types is also needed to support recording with HAL1 cameras in Android 7.
=> Support HAL1 cameras

droidmediacodec.cpp
This fixes interaction with software OMX codecs on Android 7. Use of hardware codecs depends on this commit being present in the Android source tree: https://android.googlesource.com/platform/frameworks/av/+/ca4c68f25eb61f4d4e339e99cf63f863adc52fdd%5E!/#F0
=> [video] Fix SimpleDecodingSource for video. JB#41180

Android.mk, detect_build_targets.sh, rpm/droidmedia.spec
Decide whether to build 32 bit or 64 bit libraries based on the
underlying system architecture.
Decide whether to build 32 bit or 64 bit mini-services based on the
LOCAL_32_BIT_ONLY flag in frameworks/av/media/mediaserver/Android.mk.
Fixes from JB#41777 need to be merged before this one, then this needs
to be tested locally and on obs, to make sure nothing breaks.
=> [32bit] simplify 32/64 bit builds. JB#41774

detect_build_targets.sh, rpm/droidmedia.spec
This is an abuse of the droid-make script to run an arbitrary command after the make, so the proper solution will be to factor out a droid-cmd instead, and call that from droid-make. This will do for 2.2.1 though, but should only be pushed to that.
=> [droidmedia] Temporarily fix android arch detection. JB#42355

droidmediaconstants.cpp, droidmediaconstants.h
This adds support for the format YUV420SemiPlanar which is used on mido and possibly others.
=> Add constants for OMX_COLOR_FormatYUV420SemiPlanar

Android.mk
The Android.mk contains the hardcoded path to the current directory to
include env.mk. This commit changes that to $(LOCAL_PATH) to allow
putting this repo anywhere in the Android tree. This makes including
this repo into other Android tree (e.g. Halium) easier.
=> [build] Remove hardcoded path to allow relocating the tree

services/services_9_0_0.h
[droidmedia] add two functions which where introduced between android-9.0.0_r37 and android-9.0.0_r44. JB#47101
=> droidmedia: add two functions which where introduced between android-9.0.0_r37 and android-9.0.0_r44.

allocator.cpp, droidmedia.h, droidmediabuffer.cpp, droidmediabuffer.h, droidmediacamera.cpp, droidmediacodec.cpp, hybris.c, private.cpp, private.h
We'd like to cache some buffer data on the receiving end and need
something persistent to link that too.
=> [droidmedia] Cache and re-use queue DroidMediaBuffer instances. Contributes to JB#49430

services/services_9_0_0.h
A week or so ago upstream removed the `const` qualifier from `getLayerDebugInfo()` which breaks our build if we don't update this as well.
To keep compatability with HAL not based on 9.0.0_r60 (such as Sony AOSP Hybris) we'll just duplicate the method instead, removing the `const` qualifier as per upstream.
Thanks to @NotKit for looking into this! :)
Reference:
https://github.com/LineageOS/android_frameworks_native/commit/23a8ea7cd2aa38cc28d37ae0e1e06043ec5da0b3
=> droidmedia: Fix build since android-9.0.0_r60

services/services_9_0_0.h
MediaTek has changed ISurfaceComposer in its Android 9 BSP, so droidmedia
doesn't compile without this commit.
=> [droidmedia] Fix build with MediaTek Android 9.0.0. JB#52430

AsyncDecodingSource.cpp, private.cpp
The problem is that multimedia breaks after attempt to play
5 static video in browser simultaneously. It seems that Android have
a limitation of use for 4 hardware decoders at the same time, for example
in logcat:
E osal_utils: Returns insufficientResource
E media.codec: Failed to allocate omx component 'OMX.MTK.VIDEO.DECODER.AVC'
err=InsufficientResources(0x80001000)
We need to add checking for null pointer after calling AsyncDecodingSource
constructor in Create method. We call in constructor
mCodec = MediaCodec::CreateByComponentName(mCodecLooper, mComponentName);
and in Android it can return NULL for some reasons, for example when we
try to use 5 hardware decoders simultaneously
const status_t ret = codec->init(name);
if (err != NULL) {
*err = ret;
}
return ret == OK ? codec : NULL; // …
=> [droidmedia] Add some checks for null pointer. Fixes JB#53621

droidmediacodec.cpp, droidmediacodec.h
The "prepend-sps-pps-to-idr-frames" metadata key is required to produce h264 video suitable for streaming.
=> [droidmedia] Add control over codec specific settings for avc encoder. JB#54553

droidmediacodec.cpp
ACodec::getAVCLevelFor profile parameter was changed from OMX_VIDEO_AVCPROFILETYPE to OMX_VIDEO_AVCPROFILEEXTTYPE in 8.1
=> [droidmedia] Fix build for droid versions < 8.1. JB#54553

droidmedia.cpp, droidmedia.h, hybris.c, meson.build, rpm/droidmedia-devel.spec, rpm/droidmedia.spec
Split the droidmedia-devel package into its own spec file named
droidmedia-lib. It can be built in hadware-independent projects and
applications may link against droidmedia using pkgconfig.
=> [droidmedia] Split the droidmedia package. JB#54878

droidmediacodec.cpp, droidmediacodec.h, hybris.c
This commit adds droid_media_codec_get_supported_color_formats() which
is useful for implementing a video encoder: the color format of the input
video frame must be converted to match the capabilities of the codec.
=> [droidmedia] Query the list of supported color formats. JB#55092

droidmediacodec.cpp, droidmediacodec.h
The type of colorFormats.size() varies by architecture but maxFormats
doesn't, be explicit about the type of the min function so it compiles
when the implicit types don't match.
=> [droidmedia] Fix 64 bit build. JB#55092

droidmediacamera.cpp, private.cpp
The camera on Android 8 does have setVideoTarget() method but it doesn't
work as expected, so droidmedia should use recorder callback instead of
buffer queue mode to capture raw video frames.
=> [droidmedia] Use recorder callback for Android 8. Fixes JB#55656

AsyncDecodingSource.cpp
On MediaTek devices, the default decoder input queue depth is insufficient
in some situations. The starvation of the buffer queue leads to a freeze
in the playback of some AVC-encoded videos.
This commit sets an empirically chosen value for the decoder input queue.
=> [droidmedia] Set the depth of the decoder input queue. JB#56100

droidmediaconstants.cpp
OMX_COLOR_FormatYUV420Flexible appeared in android 5 so export
this constant as equal to OMX_COLOR_FormatUnused for older versions.
=> [droidmedia] Fix build for droid versions < 5. JB#56755

AsyncCodecSource.h, droidmediacodec.cpp, mediabuffers.h
Define Buffers in a separate header so that older than Android 7 devices can include buffers separately from the ASyncCodecSource (see droidmediacodec.cpp).
Regression from SHA1 97662efa2bf0d7a800270805a945d3f4717b9a3b
=> [droidmedia] Fix build for droid versions < 7. JB#57676

droidmediacamera2.cpp
`std::to_string` (and the inverse `std::stod`) will use the active `c` locale. Qt apps do this somewhere deep inside. This resulted in the step size being printed as "0,166", which was parsed by the consumer as "0" on systems using `,` as decimal separator (eg LANG=de)
I could also copy the conversion functions from here  https://github.com/ros-planning/moveit/blob/master/moveit_core/utils/src/lexical_casts.cpp (with a suitable namespace) and use them, what do you prefer?
=> exposure: use locale independent float conversion

services/services_14_0_0.h
Duplicate setTransactionState because of change in function parameters.
=> Fix build with latest lineage-21.0

droidmediacamera2.cpp
=> interpret CONTROL_ZOOM_RATIO locale independent
